#Юра гей, ты сам андрей!
#Ахуеть это уже второй кусок #гавнокода который я где-либо выкладываю. Да....
#Если что не так с моим куском #гавнокода пишите мне в дискорд, можно в личку(Дискорд 100% был там где вы скачивали данный плагин)
#
#Что делает данный кусок #гавнокода
#Когда игрок каким либо непонятным образом, будь то консоль, или игрок с правами администратора выдал креатив, или у вас где-то утечка в правах через которую можно получить креатив, или у вас друг админ поставил командный блок на сервере через который выдаётся креатив, или в каком-то куске #гавнокода выдаётся креатив после определённого действия
#Всё что перечислено выше можно предотвратить данным плагином
#Какие режимы можно отключить:
#Креатив
#Наблюдатель
#Приключения
# Я щитаю что тупо было бы сюда вставлять режим выживания, но если хотите то добавлю :-)
#
#Все те режимы которые перечислены выше отключаются автоматически при включении данного плагина
#
#Для того что-бы разрешить игроку использовать тот или иной режим выдайте права:
#Креатив : strict.creative
#Наблюдатель : strict.spectator
#Приключения : strict.adventure
#
#Что бы этот кусок #гавнокода начал работать обязательно поставьте мне лайк за старания на том ресурсе на котором вы скачивали данное чудо
#
# Ну а дальше я хз что писать, так как будет настройка сообщений которые срабатывают когда игрок пытается перейти в тот или иной режим
#
#Для того что бы расскрасить сообщения используйте знак параграфа(мне лень его искать, поэтому если вам надо найдите сами!)

###################################
#!!! & - Это не знак параграфа !!!#
###################################

message:
  creative: "Вам запрещено пытаться перейти в режим креатив!"
  spectator: "Вам запрещено пытаться перейти в режим наблюдателя!"
  adventure: "Вам запрещено пытаться перейти в режим приключения!"
allow:
  creative: "Вы перешли в режим креатив!"
  spectator: "Вы перешли в режим наблюдателя!"
  adventure: "Вы перешли в режим приключения!"